import { Project, TaskGroup, Task } from './types';

export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'Q4 Marketing Campaign',
    color: '#3b82f6',
    description: 'Q4 마케팅 캠페인',
    startDate: '11월 12일',
    endDate: '12월 3일',
    progress: 29,
    daysRemaining: 7,
  },
  {
    id: '2',
    name: 'Website Redesign',
    color: '#8b5cf6',
    description: '웹사이트 리디자인',
    startDate: '10월 27일',
    endDate: '12월 10일',
    progress: 50,
    daysRemaining: 14,
  },
  {
    id: '3',
    name: 'Mobile App Development',
    color: '#ef4444',
    description: '모바일 앱 개발',
    startDate: '11월 26일',
    endDate: '1월 25일',
    progress: 0,
    daysRemaining: 60,
  },
];

export const mockTaskGroups: TaskGroup[] = [
  {
    id: 'tg1',
    projectId: '1',
    name: 'Content Creation',
    progress: 40,
    tasks: [
      {
        id: 't1',
        taskGroupId: 'tg1',
        projectId: '1',
        title: 'Write blog post about new features',
        status: 'completed',
        progress: 100,
        dueDate: '2025-11-28',
        createdAt: '2025-11-20',
      },
      {
        id: 't2',
        taskGroupId: 'tg1',
        projectId: '1',
        title: 'Create product demo video',
        status: 'in_progress',
        progress: 60,
        dueDate: '2025-11-29',
        createdAt: '2025-11-21',
      },
      {
        id: 't3',
        taskGroupId: 'tg1',
        projectId: '1',
        title: 'Design infographic for social media',
        status: 'todo',
        progress: 0,
        dueDate: '2025-11-30',
        createdAt: '2025-11-22',
      },
      {
        id: 't4',
        taskGroupId: 'tg1',
        projectId: '1',
        title: 'New Todo',
        status: 'todo',
        progress: 0,
        createdAt: '2025-11-27',
      },
    ],
  },
  {
    id: 'tg2',
    projectId: '1',
    name: 'Social Media Marketing',
    progress: 25,
    tasks: [
      {
        id: 't5',
        taskGroupId: 'tg2',
        projectId: '1',
        title: 'Schedule Instagram posts',
        status: 'in_progress',
        progress: 50,
        dueDate: '2025-11-28',
        createdAt: '2025-11-23',
      },
      {
        id: 't6',
        taskGroupId: 'tg2',
        projectId: '1',
        title: 'Create Twitter thread',
        status: 'todo',
        progress: 0,
        dueDate: '2025-11-29',
        createdAt: '2025-11-24',
      },
    ],
  },
  {
    id: 'tg3',
    projectId: '2',
    name: 'Design',
    progress: 70,
    tasks: [
      {
        id: 't7',
        taskGroupId: 'tg3',
        projectId: '2',
        title: 'Create homepage mockup',
        status: 'completed',
        progress: 100,
        dueDate: '2025-11-25',
        createdAt: '2025-11-15',
      },
      {
        id: 't8',
        taskGroupId: 'tg3',
        projectId: '2',
        title: 'Design product page',
        status: 'in_progress',
        progress: 80,
        dueDate: '2025-11-30',
        createdAt: '2025-11-20',
      },
    ],
  },
  {
    id: 'tg4',
    projectId: '2',
    name: 'Development',
    progress: 30,
    tasks: [
      {
        id: 't9',
        taskGroupId: 'tg4',
        projectId: '2',
        title: 'Set up Next.js project',
        status: 'completed',
        progress: 100,
        dueDate: '2025-11-20',
        createdAt: '2025-11-18',
      },
      {
        id: 't10',
        taskGroupId: 'tg4',
        projectId: '2',
        title: 'Implement responsive navigation',
        status: 'in_progress',
        progress: 40,
        dueDate: '2025-12-01',
        createdAt: '2025-11-22',
      },
      {
        id: 't11',
        taskGroupId: 'tg4',
        projectId: '2',
        title: 'Add dark mode support',
        status: 'todo',
        progress: 0,
        dueDate: '2025-12-05',
        createdAt: '2025-11-25',
      },
    ],
  },
  {
    id: 'tg5',
    projectId: '3',
    name: 'Planning',
    progress: 0,
    tasks: [
      {
        id: 't12',
        taskGroupId: 'tg5',
        projectId: '3',
        title: 'Research competitor apps',
        status: 'todo',
        progress: 0,
        dueDate: '2025-12-01',
        createdAt: '2025-11-26',
      },
    ],
  },
];
